### PR TITLE
add NM to `getModsEnum` function for convinience sake

### PR DESCRIPTION
**Pull request by yorunoken**
hopefully this doesn't break anything 😅

### CODE REVIEW

**Comment by yorunoken** [comment]
I didn't touch `getEnumMods` because it seems it already returns the mods back if the enum value is `0`, which is what `NM` would be

**Comment by L-Mario564** [comment]
Is there a specific case in which it would make a massive difference to have NM listed in the enum?
NM is an acronym that presents the fact that no mods were used to set the score, which means that any mod related property is null, undefined, or set as an empty array if no mods are set.

I ask the above question because I don't really see it removing a significant amount of code. As an example:

```ts
const mod = 0;

// Without NM in enum
const str = mods > 0 ? ModsEnum[mod] : 'NM';
// With NM in enum
const str = ModsEnum[mod];
```

It's not that big of a difference. Also, what if another dev doesn't want to display "NM", but rather just keep the value null or undefined? What if instead they want to represent NM in a different way? In those cases, the dev would have to make a check either way:

 ```ts
const str = ModsEnum[mod] === 'NM' ? 'No mods' : ModsEnum[mod];
```

**Comment by yorunoken** [comment]
I just thought it wouldn't hurt to have it, since `osu-api-extended` does it. I kinda got used to it so I felt like opening this pr since I switched to this lib

**Comment by L-Mario564** [comment]
Hmmm. The title says it handles NM with `getModsEnum` function, does that mean that you want it to behave like this?:

```ts
getModsEnum(['NM']); // Output: 0
```

**Comment by yorunoken** [comment]
yes, exactly
I also have a mod parser that tries to get `nm`, but fails because `ModsEnum` doesn't have `nm`
```ts
            const modName = "nm" // asume the parser gets `nm`
            const modSections = (/.{1,2}/g).exec(modName);

            // Make sure `modName` is an actual mod in osu!
            if (modSections && !modSections.every((selectedMod) => selectedMod.toUpperCase() in ModsEnum))
                continue;
```

**Comment by L-Mario564** [comment]
I won't be merging this PR, as NM isn't a mod, therefore, it shouldn't be in `ModsEnum`.

To help you out a bit, in the parser you have written, you can instead do:

```ts
if (modSections && !modSections.every((selectedMod) => {
  const mod = selectedMod.toUpperCase();
  return mod in ModsEnum || mod === 'NM';
}))
```

Or:

```ts
if (modSections && !modSections.every((selectedMod) => selectedMod.toUpperCase() in ModsEnum || mod === 'nm';)) 
```

**Pull request closed without merging**
